version: "3.9"

services:
  httpd:
    container_name: httpd
    image: httpd:2.4.41-alpine
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - "81:80"
    networks:
      - web_network

networks:
  web_network:
    name: httpd
    driver: bridge